[package]
name = "gddcjam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
glutin = "0.31.1"
glutin-winit = "0.4.2"
winit = { version = "0.29.3" }
